---
caddy_server_caddyfile_dest: /etc/caddy/Caddyfile
caddy_server_service:
  Caddyfile: caddy
  json: caddy-api

caddy_systemd_unit_override_directory: "/etc/systemd/system/caddy.service.d"
caddy_systemd_unit_override_dest: "{{ caddy_systemd_unit_override_directory }}/override.conf"
